# --------------------------------------------------
# Site settings
title: "Hoplon, a ClojureScript Web Framework"
logo: /assets/images/logos/hoplon-logo.png
favicon: /assets/images/logos/hoplon-favicon.png
iosicon: /assets/images/logos/hoplon-favicon.png
company: Adzerk
description: ClojureScript Web Framework
email: info@adzerk.com
copyright: Copyright © 2015 <a href="http://tailrecursion.com/~alan/">Alan Dipert</a>, <a href="https://github.com/micha">Micha Niskin</a>, <a href="https://github.com/somegoodpixels">Joshua Smith</a>
adzerk_mention: true
exclude: [vendor]

# --------------------------------------------------
# the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title
paginate: 5
paginate_path: /blog/page/:num

# --------------------------------------------------
# the base hostname & protocol for your site
url: "http://hoplon.io"
github_username: hoplon

# --------------------------------------------------
# Build settings
markdown: redcarpet
  
# --------------------------------------------------
# Build settings
defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
# --------------------------------------------------
# Links
nav: 
- title: Discourse
  href: http://hoplon.discoursehosting.net/
- title: IRC
  href: http://webchat.freenode.net/?channels=hoplon
- title: Slack
  href: http://clojurians.net/
- title: Wiki
  href: https://github.com/hoplon/hoplon/wiki
- title: Code
  href: https://github.com/hoplon
